services:
  golang:
    image: golang:1.0
    #    platform: linux/amd64
    container_name: golang
    depends_on:
      - liquibase
    ports:
      - "8084:8080"
  dotnet:
    image: dotnet:1.0
    #    platform: linux/amd64
    container_name: dotnet
    depends_on:
      - liquibase
    ports:
      - "8085:8080"
  micronaut:
    image: micronaut:1.0
#    platform: linux/amd64
    container_name: micronaut
    depends_on:
      - liquibase
    ports:
      - "8080:8080"
  quarkus:
    image: quarkus:1.0
#    platform: linux/amd64
    container_name: quarkus
    depends_on:
      - liquibase
    ports:
      - "8081:8080"
  spring-boot:
    image: spring:1.0
#    platform: linux/amd64
    container_name: spring-boot
    depends_on:
      - liquibase
    ports:
      - "8082:8080"
  helidon:
    image: helidon:1.0
#    platform: linux/amd64
    container_name: helidon
    depends_on:
      - liquibase
    ports:
      - "8083:8080"
  postgres:
    image: 'postgres:16.3'
    container_name: postgres
#    platform: linux/amd64
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - /pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: liquibase
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ./liquibase/changeLog:/liquibase/changeLog
    command: --defaults-file=/liquibase/changeLog/liquibase.properties update
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
#    platform: linux/amd64
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/promdata:/prometheus
  grafana:
    image: grafana/grafana:11.0.0-preview-ubuntu
    container_name: grafana
#    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources